name: phd-env
channels:
  - defaults
dependencies:
  - aom=3.12.1=ha237518_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py313h03d0aa3_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - contourpy=1.3.3=py313h20e30b6_0
  - cycler=0.12.1=py313hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.3=h50f4ffc_4
  - filelock=3.20.0=py313hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py313haa24f5a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.16=h8859324_0
  - fsspec=2025.12.0=py313h7eb115d_0
  - gettext=0.21.0=hbdbcc25_2
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.2=py313hbcc4bda_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.7.0=py313hca03da5_0
  - jinja2=3.1.6=py313hca03da5_0
  - jpeg=9f=h2f69dba_0
  - kiwisolver=1.4.9=py313haeee614_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250814.1=cxx17_hbea547f_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.86.3=hcacd345_0
  - libiconv=1.16=h80987f9_3
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=6.33.0=h6acce77_1
  - libtiff=4.7.1=h367c460_0
  - libtorch=2.8.0=gpu_mps_h6bb649a_201
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib=3.10.8=py313hca03da5_0
  - matplotlib-base=3.10.8=py313haa222d5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.6.1=py313hca03da5_0
  - nomkl=3.0=0
  - numexpr=2.14.1=py313h5fbe615_0
  - numpy=2.4.1=py313h4bb6f22_0
  - numpy-base=2.4.1=py313h23175f9_0
  - openssl=3.0.18=h9b4081a_0
  - opentelemetry-api=1.38.0=py313hca03da5_0
  - packaging=25.0=py313hca03da5_1
  - pandas=2.3.3=py313h3f644e9_1
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py313he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - pyparsing=3.2.5=py313hca03da5_0
  - python=3.13.11=hc7d8306_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.13=3_cp313
  - pytorch=2.8.0=gpu_mps_py313h8664c9e_201
  - pytz=2025.2=py313hca03da5_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.51.1=hab6afd1_0
  - sympy=1.14.0=py313hca03da5_1
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.4=py313haa24f5a_0
  - typing-extensions=4.15.0=py313hca03da5_0
  - typing_extensions=4.15.0=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zipp=3.23.0=py313hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/anaconda3/envs/phd-env
